Homework/blog/backend/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Homework/blog/backend/core/urls.py
from django.urls import path

from .views import AboutView, HomeView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    path('about/', AboutView.as_view(), name='about_page'),
]

Homework/blog/backend/core/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    """Base post model."""

    title = models.CharField(max_length=100)
    body = models.TextField()
    image = models.ImageField(upload_to='posts/', null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    def __str__(self):
        # EQ
        # if self.author.first_name and self.author.last_name:
        #     author = f"{self.author.first_name} {self.author.last_name}"
        # else:
        #    author = self.author
        author = (
            f"{self.author.first_name} {self.author.last_name}"
            if self.author.first_name and self.author.last_name
            else self.author
        )
        return self.title


class Comment(models.Model):
    """Base comment model."""

    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="comments", null=True, blank=True
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    text = models.CharField(max_length=255)

Homework/blog/backend/core/views.py
from django.views.generic import TemplateView
from django.views.generic import ListView
from .models import Post, Comment

class HomeView(ListView):
    """Base home view."""

    template_name = "core/home.html"
    queryset = Post.objects.all()

class AboutView(TemplateView):
    """Base about view."""

    template_name = "core/about.html"

Homework/blog/backend/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal blog</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <div class="wrapper">
        <div class="header">
            <ul class="menu">
                <li class="menu-item"><a href={% url 'core:home_page' %} style="color: white">HOME</a></li>
                <li class="menu-item"><a href={% url 'core:about_page' %} style="color: white">ABOUT</a></li>
            </ul>

            <div class="user">
                <div class="greeting">
                    Hello, USER
                </div>
   
            </div>
        <div class="user_img">
            <img src="{% static 'img/user-01.png' %}" height = 50 px weight = 50 px>
        </div>  
        </div>

    <div class="content">
        {% block content %}{% endblock content %}
    </div>

    <div class="about">
        {% block about %}{% endblock about %}
    </div>

    <div class="footer">
        <p>MIT License</p>
    </div>
    </div>
</body>
</html>

Homework/blog/backend/templates/core/about.html
{% extends 'base.html' %}
{% load static %}
{% block about %}
<div class="about">
    <div class about-text>
        <P><br>Python is an interpreted, high-level and general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.</P>
        <P><br><br>Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly, procedural), object-oriented and functional programming. Python is often described as a "batteries included" language due to its comprehensive standard library.</P>
        <P><br><br>Python was created in the late 1980s, and first released in 1991, by Guido van Rossum as a successor to the ABC programming language. Python 2.0, released in 2000, introduced new features, such as list comprehensions, and a garbage collection system with reference counting, and was discontinued with version 2.7 in 2020.[31] Python 3.0, released in 2008, was a major revision of the language that is not completely backward-compatible and much Python 2 code does not run unmodified on Python 3. With Python 2's end-of-life (and pip having dropped support in 2021[32]), only Python 3.6.x[33] and later are supported, with older versions still supporting e.g. Windows 7 (and old installers not restricted to 64-bit Windows).</P>
        <P><br><br>Python interpreters are supported for mainstream operating systems and available for a few more (and in the past supported many more). A global community of programmers develops and maintains CPython, a free and open-source[34] reference implementation. A non-profit organization, the Python Software Foundation, manages and directs resources for Python and CPython development.</P>
    </div>
    <p class="about-img"><img src="{% static 'img/user-01.png' %}" width = 350 px></p>
</div>
{% endblock about %}

Homework/blog/backend/templates/core/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="content">
    <div class="posts">
        {% for Post in object_list %}
        <div class="post">
            <p class='post_img'> <img src="{{Post.image.url}}"height = 100px> </p>
            <p class="post-title">{{Post.title}}</p>
            <p class="post-body">{{Post.body}}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}